### ISSUE TITLE
Issue with keras-deep-dream.py 

### ISSUE THREAD

**Issue by DonovanJames** [lukas/ml-class#12]
Getting an error when trying to compile deep dream. Maybe an issue with py 2.7? 

Gibson:ml-class usbots$ python keras-deep-dream.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "keras-deep-dream.py", line 54, in <module>
    model = inception_v3.InceptionV3(weights='imagenet', include_top=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/applications/inception_v3.py", line 386, in InceptionV3
    model.load_weights(weights_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 2531, in load_weights
    raise ImportError('`load_weights` requires h5py.')
ImportError: `load_weights` requires h5py.
Gibson:ml-class usbots$ python keras-deep-dream.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "keras-deep-dream.py", line 55, in <module>
    include_top=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/applications/inception_v3.py", line 386, in InceptionV3
    model.load_weights(weights_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 2531, in load_weights
    raise ImportError('`load_weights` requires h5py.')
ImportError: `load_weights` requires h5py.

**Comment by DonovanJames** [comment]
Found the issues. vgg16_weights.h5 failed to download.
