### ISSUE TITLE
no module named 'win32api' on 64 bit python

### ISSUE THREAD

**Issue by nstafford** [lukas/ml-class#46]
Just starting on python and ML.  I am working through the first example.  I have 64bit anaconda python 3.7, I had to create a 3.6 conda environment to get keras etc to install.  Then executing ex 1, I got the following (Is this just a 64bit python problem? and I need 32bit python?):
Traceback (most recent call last):
  File "perceptron-single.py", line 10, in <module>
    run = wandb.init()
  File "C:\Anaconda3\envs\ml-class\lib\site-packages\wandb\__init__.py", line 1051, in init
    _init_headless(run)
  File "C:\Anaconda3\envs\ml-class\lib\site-packages\wandb\__init__.py", line 223, in _init_headless
    import win32api
ModuleNotFoundError: No module named 'win32api'

Thanks,
Neil

**Comment by nstafford** [comment]
Fixed.  I had to "pip install pypiwin32" and then later on I had to "conda install pilllow" and after that it is working!
